### PR TITLE
Add extra volumes extra volume mounts

### PR DESCRIPTION
**Pull request by mkatana-silkycoders**
Mount additional volumes like files, for example to read LDAP configuration file via:

```
GF_AUTH_LDAP_ENABLED=true
GF_AUTH_LDAP_CONFIG_FILE=/<path>/ldap.toml
```

References:
- https://www.percona.com/blog/enable-ldap-on-percona-monitoring-and-management-pmm/

### CODE REVIEW

**Comment by spron-in** [comment]
Looks valid to me.

**Review by spron-in — DISMISSED** [review]

**Review by gen1us2k — APPROVED** [review]
Thank you for your contribution. Looks good to me

**Comment by mkatana-silkycoders** [comment]
@spron-in help :D?

**Comment by mkatana-silkycoders** [comment]
@spron-in help :D?

**Comment by mkatana-silkycoders** [comment]
@spron-in and @gen1us2k i had to bump version, other PR already bumped...

**Comment by zhimsel** [comment]
@spron-in @gen1us2k any updates on getting this merged? I could definitely use this feature ASAP 😄

**Review by gen1us2k — DISMISSED** [review]

**Comment by georgekaz** [comment]
Is this stuck (lint-test) ? I could also do with this asap so I can implement custom-queries as per https://grafana.com/grafana/dashboards/11874-posgresql-db-table-size-details-designed-for-pmm/

It would be nice if an extra configmap could be added to contain the contents of these query (or other) files too. At the moment the configmap is only for env vars.

**Comment by mkatana-silkycoders** [comment]
@spron-in help

**Comment by edithturn** [comment]
Hi @mkatana-silkycoders, I am inquiring about this PR through our Percona channels. Meanwhile I want to share some comments regarding this PR. 

I have replicated all your changes in my branch https://github.com/edithturn/percona-helm-charts/actions/runs/6175935896/job/16763816017 . This is in order to see the GitHub workflow logs in more depth, something that I can´t see in this Actions workflow.

I encountered an issue where the tests did not pass "Run chart-testing (lint)":

` ✖︎ pmm => (version: "1.2.5", path: "charts/pmm") > chart version not ok. It needs a version bump! `

However, after adjusting the version of the PMM Chart to 2.2.5, it started working. 
If I am correct, may you give it a try? Please let me know your comments.

Thanks!

**Comment by mkatana-silkycoders** [comment]
> Hi @mkatana-silkycoders, I am inquiring about this PR through our Percona channels. Meanwhile I want to share some comments regarding this PR.
> 
> I have replicated all your changes in my branch https://github.com/edithturn/percona-helm-charts/actions/runs/6175935896/job/16763816017 . This is in order to see the GitHub workflow logs in more depth, something that I can´t see in this Actions workflow.
> 
> I encountered an issue where the tests did not pass "Run chart-testing (lint)":
> 
> `✖︎ pmm => (version: "1.2.5", path: "charts/pmm") > chart version not ok. It needs a version bump!`
> 
> However, after adjusting the version of the PMM Chart to 2.2.5, it started working. If I am correct, may you give it a try? Please let me know your comments.
> 
> Thanks!

I bumped version of app not chart, my mistake.. thanks, fixed..

**Comment by edithturn** [comment]
Thank you @mkatana-silkycoders.
Please confirm if my statement is accurate.

In Chart.yaml we have the field: `version: 1.2.6`, which is the version of the chart.

I was checking when this field should be modified. This is what I found:

> Whenever you make significant changes to the Helm chart itself, such as modifying the chart's templates, values, or dependencies, you should update the version to reflect the new version of the chart.

If I'm correct, you modified the Chart.yaml, then you should also change the Chart version to `version: 1.2.6`
Example: https://github.com/edithturn/percona-helm-charts/actions/runs/6180874472/job/16778004721

**Review by BupycHuk — APPROVED** [review]

**Comment by mkatana-silkycoders** [comment]
> Thank you @mkatana-silkycoders. Please confirm if my statement is accurate.
> 
> In Chart.yaml we have the field: `version: 1.2.6`, which is the version of the chart.
> 
> I was checking when this field should be modified. This is what I found:
> 
> > Whenever you make significant changes to the Helm chart itself, such as modifying the chart's templates, values, or dependencies, you should update the version to reflect the new version of the chart.
> 
> If I'm correct, you modified the Chart.yaml, then you should also change the Chart version to `version: 1.2.6` Example: https://github.com/edithturn/percona-helm-charts/actions/runs/6180874472/job/16778004721

yep i changed chart version to 1.3.0 from 1.2.5, my changes are like feature not bug bugfix, so version 1.3.0 will be more appropriate than 1.2.6

**Review by gen1us2k — APPROVED** [review]

**Pull request merged**
