### PR TITLE
PMM-9946 Added additional rules to service account

### PR DESCRIPTION
**Pull request by gen1us2k**
* Added serviceaccounts to get token name
* Added secrets to get access to secrets

### CODE REVIEW

**Review by denisok — DISMISSED** [review]

**Comment by denisok** [comment]
@gen1us2k  I think version is outdated, please update

**Review by tplavcic — DISMISSED** [review]

**Comment by denisok** [comment]
@gen1us2k please resolve conflicts

**Comment by gen1us2k** [comment]
@denisok Fixed it.

**Review by denisok — APPROVED** [review]

**Review by denisok — DISMISSED** [review]

**Comment by gen1us2k** [comment]
Now it's a complete set of rules that are required for PMM to run using a service account

**Review by denisok — APPROVED** [review]
wow, that is extensive cluster role :)

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
