### PR TITLE
CLOUD-838 - Fix dataVolumeClaimSpec...storage in README

### PR DESCRIPTION
**Pull request by mrrsm**
`instances.walVolumeClaimSpec.resources.requests.storage` was duplicated for dataVolumeClaimSpec

### CODE REVIEW

**Comment by egegunes** [comment]
@mrrsm please bump the version

**Review by spron-in — DISMISSED** [review]

**Comment by mrrsm** [comment]
@egegunes Do you want a version bump for a docs only change?

**Comment by egegunes** [comment]
@tplavcic does the requirement for bump caused by the lint-test check or does helm require bump for README change?

**Comment by tplavcic** [comment]
@egegunes @mrrsm Each change in helm charts triggers release so the version needs to be bumped since we cannot re-release old version. I agree it's a bit silly in this case, I'll check if chart releaser and linter can be configured differently, but for now it is like this.

**Review by tplavcic — APPROVED** [review]

**Comment by tplavcic** [comment]
Thank you very much for the contribution!

**Pull request merged**
