### PR TITLE
Specify storageClassName

### PR DESCRIPTION
**Pull request by kirillvelikov**
This PR allows users to specify custom storageClassName for the:
* PostgreSQL storage
* Write-ahead Log
* pgBackRest volume

### CODE REVIEW

**Comment by discostur** [comment]
@kirillvelikov can you say when this will get merged? this is really critical for production use ... ;)

**Comment by egegunes** [comment]
@kirillvelikov could you please fix conflicts and bump version?

**Review by spron-in — APPROVED** [review]

**Comment by discostur** [comment]
@kirillvelikov I still cannot see this in the newest chart version ... could you please make a  new release?

**Comment by tplavcic** [comment]
@kirillvelikov Can you please reopen this PR or I will create another one since it seems this was not merged.

**Pull request closed without merging**
