### PR TITLE
K8SPG-644 - Fix tolerations iteration issue for pg-db cluster template

### PR DESCRIPTION
**Pull request by kv-dhyey-moliya**
Currently the cluster template incorrectly takes only single value (object) for tolerations instead of accepting an array of objects. 

There is already an issue for this : https://github.com/percona/percona-helm-charts/issues/333
This PR fixes that issue by updating the template code that Instead of replacing with single value, replaces array of tolerations for pg-db cluster template.

### CODE REVIEW

**Review by tplavcic — CHANGES_REQUESTED** [review]
Thank you for the contribution! Please bump the chart version.

**Comment by kv-dhyey-moliya** [comment]
This fix might break the existing setup of users as the workaround was to put single `map` under tolerations, and it would work. But the fix makes the chart use `range`. 

What should be ideal version bump in this case? Do the charts use semantic versioning? Then it might require to increase major version due to incompatibility with older versions. Changing major version seems like an overkill.

Or else we can resort to conditional logic if the user passes array, use the array, else use the direct map values as shown below.
```
tolerations:
{{- $tolerations := .Values.mapItems }}
{{- if eq (kindOf $tolerations) "map" }}
  - key1: {{ $tolerations.key1 }}
    key2: {{ $tolerations.key2 }}
{{- else}}
{{- range .Values.mapItems }}
  - key1: {{ .key1 }}
    key2: {{ .key2 }}
{{- end }}
{{- end}}
```

Please suggest.

**Comment by tplavcic** [comment]
@kv-dhyey-moliya Usually we bump the "patch" version, but if it's something that breaks compatibility then we merge it on the next operator release when the "minor" version is bumped. At the current moment we do not bump "major" version at all. Basically our helm chart versions follow the operator version except that we can bump the "patch" version if there's a small fix just for the helm chart.
So I propose for your change that we merge it on the next PG operator release.

**Comment by kv-dhyey-moliya** [comment]
@tplavcic thank you for the update. Then, should I update the chart version to a major version for this PR? Or leave it as it is for now?

Additionally, As per my other suggestion, we can make it backwards compatible if we do conditional check, then we can update with a patch version, but again that will add unnecessary conditional code into the codebase. Ping me if you feel it's ok for now to add the conditional code, then I'll update it accordingly with a patch version.

**Comment by tplavcic** [comment]
I think just leave it for now, when we will work on the next release we will merge your fix to the release branch and make any additional changes needed.

**Review by jvpasinatto — APPROVED** [review]

**Pull request merged**
