### PR TITLE
add the option to load env from a external secet

### PR DESCRIPTION
**Pull request by KyriosGN0**
the reasom is that today, when using an existing secret, we can't put different values from the ones that are in the created secret. 
this will allow users to use an external secret (for example with external-secrets operator) and put any required variables as env vars

### CODE REVIEW

**Comment by spron-in** [comment]
I like it. @BupycHuk what do you think?

**Review by BupycHuk — DISMISSED** [review]
Looks good to me, please fix conflicts and update readme

**Comment by KyriosGN0** [comment]
@BupycHuk fixed conflicts, updated readme (although im not sure where should i have updated it)

**Comment by KyriosGN0** [comment]
@BupycHuk possibly any updates here?

**Review by BupycHuk — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
