### PR TITLE
K8SPSMDB-598 Fix backup.resources indentation.

### PR DESCRIPTION
**Pull request by antoineozenne**

### CODE REVIEW

**Comment by tplavcic** [comment]
Hi @antoineozenne !
Thank you for the ticket and the fix! Could you please sign the CLA so I can merge this PR.

**Comment by antoineozenne** [comment]
Hi @tplavcic, I already signed the CLA 10 times, but nothing is happening.

**Comment by tplavcic** [comment]
@antoineozenne Please check if following email address which was used to make commits is added to your github account `Antoine Ozenne <antoine.ozenne@itga.fr>`. If not you'll need to add it or if that is not possible then make commits with email which exists in your github account and overwrite the branch or create a new PR.

**Comment by antoineozenne** [comment]
@tplavcic, thanks, and sorry, it was a miss. I changed the commit author.

**Review by tplavcic — APPROVED** [review]

**Comment by tplavcic** [comment]
Thank you!

**Pull request merged**
